[project]
name = "semi-fungible-token"
description = "A concept semi-fungible token standard and reference implementation for the Stacks blockchain based on SIP13."
authors = []
telemetry = false
cache_dir = "./.cache"

[[project.requirements]]
contract_id = "SPDBEG5X8XD50SPM1JJH0E5CTXGDV5NJTKAKKR5V.sip013-semi-fungible-token-trait"

[[project.requirements]]
contract_id = "SPDBEG5X8XD50SPM1JJH0E5CTXGDV5NJTKAKKR5V.sip013-transfer-many-trait"

[contracts.semi-fungible-token]
path = "contracts/semi-fungible-token.clar"
clarity_version = 4
epoch = "latest"
